Ot135 43 logging b
alkemyTech/OT135-Proyecto-1 pull request #32
Opened 2022-02-01 20:20 UTC by nvrancovich

Configuring logs for the group of universities b

2022-02-01 20:20 UTC, nvrancovich commented
https://alkemy-labs.atlassian.net/browse/OT135-43

2022-02-02 00:23 UTC, julianpalmerio requested changes

2022-02-02 00:23 UTC, julianpalmerio commented on dag-universities-b.py
> +log.basicConfig(level=log.ERROR, format='%Y-%m-%d:%(processName)s:%(message)s')
Revisa la configuración del log, el format no esta bien implementado.

2022-02-02 12:53 UTC, nvrancovich commented on dag-universities-b.py
> +log.basicConfig(level=log.ERROR, format='%Y-%m-%d:%(processName)s:%(message)s')
Tengo un problema con Airflow pero vi los pull request de mis compañeros y lo hicieron como lo corregí recién.

2022-02-02 13:06 UTC, julianpalmerio commented on dag-universities-b.py
> +log.basicConfig(level=log.ERROR, format='%Y-%m-%d:%(processName)s:%(message)s')
Dale, ahora esta bien!

2022-02-02 13:09 UTC, merged