Added Python Operator (SQL)
alkemyTech/OT135-Proyecto-1 pull request #34
Opened 2022-02-03 20:44 UTC by hectornauta

Añadí el Python Operator que ejecuta el archivo SQL y genera el archivo CSV correspondiente
* Hice unos cambios insignificantes en el estilo de código del DAG, para que quede uniforme con pep8
* Tuve que especificar la versión de Pandas al instalarlo mediante pip. Al parecer pandas 1.4.0 requiere una versión de SqlAlchemy >1.4. pero el flask-appbuilder (que supongo es el que se usa para crear la web de Airflow) requiere SqlAlchemy <1.4.
En resumen, que al instalar hay que especificar la versión haciendo pip install pandas 1.3.5 para que funcione sin romper dependencias
* Añadí los paths a carpetas/archivos debido a que surgían errores al leer/escribir los archivos

2022-02-07 21:28 UTC, julianpalmerio commented
Hector, veo el codigo bien, unos pequeños comentarios.

Estas usando sys.exit() pero no estas importando sys. Como el código no falla no te llega a tirar el error, pero si en algún momento entrara en alguno de los try except, fallaría.

Por otro lado, me parece mas apropiado en lugar de hacer un sys.exit(), dejar un log, como ya haces, y hacer un raise ex. De esta forma ariflow puede gestionar mejor la excepción.

El .env funciona bien, pero dejar un template.cfg y tener que renombrarlo como .env confunde un poco, por que no template.env?.

2022-02-07 21:28 UTC, julianpalmerio requested changes
Te deje un comentario. En la conver.

2022-02-08 00:09 UTC, julianpalmerio requested changes

2022-02-08 00:09 UTC, julianpalmerio commented on dag_universities_c.py
> +
Generalmente es mejor instanciar el logger antes que nada en el codigo.

2022-02-08 00:09 UTC, julianpalmerio commented on dag_universities_c.py
> +    PATH_TO_CSV_FILES = DIR + '/files'
Es un poco mas facil de leer el codigo si los strings los escribimos con format o con fstrings. por ejemplo aqui se mas lindo escribir PATH_TO_CSV_FILES = f'{DIR}/files'

2022-02-08 00:09 UTC, julianpalmerio commented on dag_universities_c.py
> +    PATH_TO_CSV_FILES = DIR + '/files'
Esto aplicalo a todas las concatenaciones de strings en el resto del codigo.

2022-02-08 00:09 UTC, julianpalmerio commented on dag_universities_c.py
> +        sys.exit('Ha ocurrido un error al leer los archivos SQL')
Como te dije en el comentario de la conver general, en lugar de sys exit, es mejor hacer un raise e

2022-02-08 05:12 UTC, hectornauta commented
Realizados los cambios solicitados

2022-02-08 13:19 UTC, merged